# Generated by Django 5.1.15 on 2026-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tvet", "TVET"),
                            ("maritime", "Maritime"),
                            ("engineering", "Engineering"),
                        ],
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertiseCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome class e.g. fas fa-ship", max_length=100
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("subtitle", models.TextField()),
                ("button_text", models.CharField(max_length=100)),
                ("button_url", models.CharField(default="#", max_length=200)),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("accent", "Accent"),
                            ("secondary", "Secondary"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("background_image", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("ongoing", "Ongoing")],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(default="contact@niikpakpo.com", max_length=254),
                ),
                ("location", models.CharField(default="Accra, Ghana", max_length=200)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                (
                    "home_about_title",
                    models.CharField(
                        default="About Edgar Nii Kpakpo Addo", max_length=200
                    ),
                ),
                (
                    "home_about_p1",
                    models.TextField(
                        default="Edgar Nii Kpakpo Addo is a distinguished Maritime Education Practitioner, Certified Engineer, and Entrepreneur with a passion for shaping the future of the TVET, maritime, and oil & gas industries. With a career spanning over two decades, he bridges academic excellence with real-world impact."
                    ),
                ),
                (
                    "home_about_p2",
                    models.TextField(
                        default="As a lecturer at the Regional Maritime University and a consultant for international institutions, he is a driving force behind competency-based technical and vocational training in Ghana. His mission is to make hands-on technical education the catalyst for Ghana's economic transformation."
                    ),
                ),
                (
                    "quote_banner",
                    models.TextField(
                        default="My mission is simple: make hands-on technical education the driving force of Ghana's economic transformation."
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(default="Join the Vision", max_length=200),
                ),
                (
                    "cta_body",
                    models.TextField(
                        default="Let's connect and explore opportunities for collaboration, growth, and transforming Ghana's technical education landscape together."
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
