# Generated by Django 5.1.15 on 2026-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Edgar Nii Kpakpo Addo", max_length=100),
        ),
    ]
