# Generated by Django 5.1.15 on 2026-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blogpost_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tag",
                        help_text="FontAwesome class",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
