# Generated by Django 5.1.15 on 2026-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="home_about_image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
