# Generated by Django 5.2.4 on 2026-04-08 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("counselling_types", models.CharField(blank=True, max_length=500)),
                (
                    "payment_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free_only", "Free only"),
                            ("freemium", "Freemium"),
                            ("subscription", "Monthly subscription"),
                            ("per_session", "Pay per session"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_willingness", models.CharField(blank=True, max_length=10)),
                (
                    "age_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under18", "Under 18"),
                            ("18-24", "18 – 24"),
                            ("25-34", "25 – 34"),
                            ("35-44", "35 – 44"),
                            ("45-54", "45 – 54"),
                            ("55+", "55+"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sources", models.CharField(blank=True, max_length=200)),
                ("extra_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey",
                        to="waitlist.registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Response",
                "verbose_name_plural": "Survey Responses",
                "ordering": ["-created_at"],
            },
        ),
    ]
